<a href="https://colab.research.google.com/github/Mattalukkal/Ai_ML/blob/main/Numpy_Practice_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.

In [2]:
import numpy as np


In [3]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
arr1.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

2. Create an array of 10 zeros and replace the 5th element with 100.

In [6]:
arr = np.zeros(10)
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr[4] = 100
arr

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

3. Create a NumPy array of even numbers between 2 and 40."

In [9]:
array2 = np.arange(2,41,2)
array2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

 4. Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.

In [15]:
np.random.seed(42)
random_int = np.random.randint(1,101,15)
random_int

array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88, 100,  24,
         3,  22])

In [16]:
random_int.min()

np.int64(3)

In [17]:
random_int.max()


np.int64(100)

In [18]:
random_int.mean()


np.float64(58.06666666666667)

In [19]:

random_int.std()

np.float64(31.4843170836247)

 5. Given two arrays of sales and costs, calculate profit and profit percentage arrays.

> Add blockquote



In [26]:

costs = np.array([80, 210, 730, 140, 350])
sales = np.array([1000, 2000, 3000, 4000, 5000])

profit = sales - costs
profit

array([ 920, 1790, 2270, 3860, 4650])

In [29]:
profit_percentage = (profit / sales) * 100
profit_percentage.round(2)
profit_percentage


array([92.        , 89.5       , 75.66666667, 96.5       , 93.        ])

   6. Create a 6×6 random matrix and compute row sums, column sums, and total sum.

In [31]:

np.random.seed(10)

Matrix = np.random.randint(1,100, size=(6,6))
Matrix

array([[10, 16, 65, 29, 90, 94],
       [30,  9, 74,  1, 41, 37],
       [17, 12, 55, 89, 63, 34],
       [73, 79, 50, 52, 55, 78],
       [70, 14, 26, 14, 93, 87],
       [31, 31, 90, 13, 66, 32]])

In [32]:
print("Row sum :" ,Matrix.sum(axis=1))


Row sum : [304 192 270 387 304 263]


In [33]:
print("Column sum: ", Matrix.sum(axis=0))


Column sum:  [231 161 360 198 408 362]


In [34]:
print(" total sum:" ,Matrix.sum())


 total sum: 1720


7.Given stock prices, compute daily returns using vectorized NumPy operations.

In [36]:

prices = np.array([91, 89, 115, 112, 109, 111, 81])
daily_returns = (prices[1:] - prices[:-1]) / prices[:-1]
print("Stock Prices:", prices)
print("Daily Returns:", daily_returns.round(4))

Stock Prices: [ 91  89 115 112 109 111  81]
Daily Returns: [-0.022   0.2921 -0.0261 -0.0268  0.0183 -0.2703]


8. Convert an array of annual interest rates into monthly rates using vectorization.

In [38]:
annual_rates = np.array([0.10, 0.11, 0.12, 0.13])
monthly_rates = annual_rates / 12
print("Annual Interest Rates:", annual_rates)
print("Monthly Interest Rates:", monthly_rates.round(4))

Annual Interest Rates: [0.1  0.11 0.12 0.13]
Monthly Interest Rates: [0.0083 0.0092 0.01   0.0108]


   9. Normalize a given array of portfolio weights so that the sum becomes 1.

In [39]:

weights = np.array([100, 200, 300, 400,500])
normalized_weights = weights / weights.sum()
print("weights:", weights)
print("sum=1:", normalized_weights.round(4))


weights: [100 200 300 400 500]
sum=1: [0.0667 0.1333 0.2    0.2667 0.3333]


10.Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]
* a.Find:
* i.mean
* ii.max
* iii.index of the max value

In [60]:
import pandas as pd

In [56]:
data_list = [1200, 1500, 1800, 2000, 2200]
series = pd.Series(data_list)
print("Pandas Series:")
display(series)

Pandas Series:


0    1200
1    1500
2    1800
3    2000
4    2200
dtype: int64

In [57]:
mean_value = series.mean()
print("Mean of the Series:")
display(mean_value)

Mean of the Series:


np.float64(1740.0)

In [59]:
max_value = series.max()
index_of_max = series.idxmax()
print("Maximum value of the Series:")
display(max_value)
print("Index of the maximum value:")
display(index_of_max)

Maximum value of the Series:


2200

Index of the maximum value:


4

11.Create a DataFrame with Student Name + 3 subject marks:
Name | Math | Science | English
Then:
* Print only the Math column
* Print first 2 rows
* Print the shape

In [70]:
data = {
    'Name': ['Ram', 'Raj', 'Ravi', 'Rani'],
    'Math': [85, 90, 78, 92],
    'Science': [79, 88, 85, 90],
    'English': [90, 82, 88, 75]
}
df_students = pd.DataFrame(data)
print("Student DataFrame:")
display(df_students)

Student DataFrame:


Name  Math  Science  English
0   Ram    85       79       90
1   Raj    90       88       82
2  Ravi    78       85       88
3  Rani    92       90       75

In [71]:
print("Math Column:")
display(df_students['Math'])

Math Column:


0    85
1    90
2    78
3    92
Name: Math, dtype: int64

In [72]:
print("First 2 rows of the DataFrame:")
display(df_students.head(2))

First 2 rows of the DataFrame:


Name  Math  Science  English
0  Ram    85       79       90
1  Raj    90       88       82

In [73]:
print("Shape of the DataFrame:")
display(df_students.shape)

Shape of the DataFrame:


(4, 4)

12.Using this DataFrame:

df = pd.DataFrame({
    "Account": [101,102,103,104],
    "Balance": [5000, 15000, 7000, 12000]
})

Filter rows where:
* Balance > 8000
* Balance between 6000 and 13000

In [77]:
print("Rows where Balance > 8000:")
display(df[df['Balance'] > 8000])

Rows where Balance > 8000:


Account  Balance
1      102    15000
3      104    12000

In [76]:
print("Rows where Balance is between 6000 and 13000:")
display(df[(df['Balance'] >= 6000) & (df['Balance'] <= 13000)])

Rows where Balance is between 6000 and 13000:


Account  Balance
2      103     7000
3      104    12000